export const UserRole = {
    ADMIN: 'ADMIN',
    ADMIN_READ_ONLY: 'ADMIN_READ_ONLY',
    ADMIN_USER_MANAGER: 'ADMIN_USER_MANAGER',
    ADMIN_CONTENT_MANAGER: 'ADMIN_CONTENT_MANAGER',
    SKKU_MEMBER: 'SKKU_MEMBER',
    EXTERNAL_MEMBER: 'EXTERNAL_MEMBER'
};
